name: Terraform CD - Prod

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  plan-prod:
    name: Plan for Prod
    runs-on: ubuntu-latest
    environment: prod
    env:
      TF_VAR_container_name: ${{ vars.TFSTATE_CONTAINER_NAME }}
      TF_VAR_env: prod
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      # 1. OIDC Login
      - name: Azure Login (Prod)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 2. Configure Env for Terraform OIDC
      - name: Configure Env for Terraform OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      # 3. Setup Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # 4. Terraform Init
      - name: Terraform Init (Prod)
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="container_name=prod-tfstate" \
            -backend-config="key=multilayer-webapp.tfstate"

      # 5. Terraform Plan
      - name: Terraform Plan (Prod)
        working-directory: terraform
        run: |
          terraform plan -out=prod.tfplan

      # 6. Upload Plan Artifact
      - name: Upload Terraform Plan for Review
        uses: actions/upload-artifact@v3
        with:
          name: terraform-prod-plan
          path: terraform/prod.tfplan

  apply-prod:
    name: Apply to Prod
    runs-on: ubuntu-latest
    needs: plan-prod
    environment: prod
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Azure Login (Prod)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Env for Terraform OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init (Prod)
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="container_name=prod-tfstate" \
            -backend-config="key=multilayer-webapp.tfstate"

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-prod-plan
          path: terraform

      - name: Terraform Apply (Prod)
        working-directory: terraform
        run: terraform apply -auto-approve prod.tfplan
