name: "Terraform Plan (Prod)"

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  plan-prod:
    name: "Plan for Prod"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - name: Azure Login (Prod)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Env for Terraform OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init (Prod)
        working-directory: terraform
        env:
          TF_VAR_container_name: ${{ vars.TFSTATE_CONTAINER_NAME }}
          TF_VAR_env: prod
        run: |
          terraform init \
            -backend-config="container_name=${TF_VAR_container_name}" \
            -backend-config="key=multilayer-webapp-prod.tfstate"

      - name: Terraform Plan (Prod)
        working-directory: terraform
        env:
          TF_VAR_container_name: ${{ vars.TFSTATE_CONTAINER_NAME }}
          TF_VAR_env: prod
        run: terraform plan -out=prod.tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-prod-plan
          path: terraform/prod.tfplan
