name: "Terraform Apply (Dev)"

on:
  workflow_run:
    workflows: ["Terraform Plan (Dev)"]
    types: [completed]

permissions:
  contents: read
  id-token: write

jobs:
  apply-dev:
    if: github.event.workflow_run.conclusion == 'success'
    name: "Apply to Dev"
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: (Manual Approval Required) Wait for Dev Approval
        run: echo "This job will pause until the dev environment is approved via GitHub Environment Protection Rules."
      
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Azure Login (Dev)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Env for Terraform OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Download Dev Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-dev-plan
          path: terraform/dev.tfplan

      - name: Terraform Init (Dev)
        working-directory: terraform
        env:
          TF_VAR_container_name: ${{ vars.TFSTATE_CONTAINER_NAME }}
          TF_VAR_env: dev
        run: |
          terraform init \
            -backend-config="container_name=${TF_VAR_container_name}" \
            -backend-config="key=multilayer-webapp-dev.tfstate"

      - name: Terraform Apply (Dev)
        working-directory: terraform
        env:
          TF_VAR_container_name: ${{ vars.TFSTATE_CONTAINER_NAME }}
          TF_VAR_env: dev
        run: terraform apply -auto-approve dev.tfplan
