name: Terraform CI

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['feature/*', 'bugfix/*', 'hotfix/*']

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Validate
        run: terraform validate

      - name: Lint with TFLint
        run: tflint --init && tflint

      - name: Run Checkov (Optional)
        run: checkov -d .
